//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace CJH.CJHToolForWin.WS_Area {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CJHWServiceBaseSoap", Namespace="http://tempuri.org/")]
    public partial class CJHWServiceBase : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAreaNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAreaCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProvincesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCountyOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveHHTAreaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHHTAreaRemarkOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHHTAreaListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CJHWServiceBase() {
            this.Url = global::CJH.CJHToolForWin.Properties.Settings.Default.CJHToolForWin_WS_Area_CJHWServiceBase;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAreaNameCompletedEventHandler GetAreaNameCompleted;
        
        /// <remarks/>
        public event GetAreaCodeCompletedEventHandler GetAreaCodeCompleted;
        
        /// <remarks/>
        public event GetProvincesCompletedEventHandler GetProvincesCompleted;
        
        /// <remarks/>
        public event GetCityCompletedEventHandler GetCityCompleted;
        
        /// <remarks/>
        public event GetCountyCompletedEventHandler GetCountyCompleted;
        
        /// <remarks/>
        public event SaveHHTAreaCompletedEventHandler SaveHHTAreaCompleted;
        
        /// <remarks/>
        public event GetHHTAreaRemarkCompletedEventHandler GetHHTAreaRemarkCompleted;
        
        /// <remarks/>
        public event GetHHTAreaListCompletedEventHandler GetHHTAreaListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAreaName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAreaName(string code) {
            object[] results = this.Invoke("GetAreaName", new object[] {
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAreaNameAsync(string code) {
            this.GetAreaNameAsync(code, null);
        }
        
        /// <remarks/>
        public void GetAreaNameAsync(string code, object userState) {
            if ((this.GetAreaNameOperationCompleted == null)) {
                this.GetAreaNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAreaNameOperationCompleted);
            }
            this.InvokeAsync("GetAreaName", new object[] {
                        code}, this.GetAreaNameOperationCompleted, userState);
        }
        
        private void OnGetAreaNameOperationCompleted(object arg) {
            if ((this.GetAreaNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAreaNameCompleted(this, new GetAreaNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAreaCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAreaCode(string areaname) {
            object[] results = this.Invoke("GetAreaCode", new object[] {
                        areaname});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAreaCodeAsync(string areaname) {
            this.GetAreaCodeAsync(areaname, null);
        }
        
        /// <remarks/>
        public void GetAreaCodeAsync(string areaname, object userState) {
            if ((this.GetAreaCodeOperationCompleted == null)) {
                this.GetAreaCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAreaCodeOperationCompleted);
            }
            this.InvokeAsync("GetAreaCode", new object[] {
                        areaname}, this.GetAreaCodeOperationCompleted, userState);
        }
        
        private void OnGetAreaCodeOperationCompleted(object arg) {
            if ((this.GetAreaCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAreaCodeCompleted(this, new GetAreaCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProvinces", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetProvinces() {
            object[] results = this.Invoke("GetProvinces", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProvincesAsync() {
            this.GetProvincesAsync(null);
        }
        
        /// <remarks/>
        public void GetProvincesAsync(object userState) {
            if ((this.GetProvincesOperationCompleted == null)) {
                this.GetProvincesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProvincesOperationCompleted);
            }
            this.InvokeAsync("GetProvinces", new object[0], this.GetProvincesOperationCompleted, userState);
        }
        
        private void OnGetProvincesOperationCompleted(object arg) {
            if ((this.GetProvincesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProvincesCompleted(this, new GetProvincesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCity(string pcode) {
            object[] results = this.Invoke("GetCity", new object[] {
                        pcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCityAsync(string pcode) {
            this.GetCityAsync(pcode, null);
        }
        
        /// <remarks/>
        public void GetCityAsync(string pcode, object userState) {
            if ((this.GetCityOperationCompleted == null)) {
                this.GetCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCityOperationCompleted);
            }
            this.InvokeAsync("GetCity", new object[] {
                        pcode}, this.GetCityOperationCompleted, userState);
        }
        
        private void OnGetCityOperationCompleted(object arg) {
            if ((this.GetCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCityCompleted(this, new GetCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCounty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCounty(string pcode) {
            object[] results = this.Invoke("GetCounty", new object[] {
                        pcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCountyAsync(string pcode) {
            this.GetCountyAsync(pcode, null);
        }
        
        /// <remarks/>
        public void GetCountyAsync(string pcode, object userState) {
            if ((this.GetCountyOperationCompleted == null)) {
                this.GetCountyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountyOperationCompleted);
            }
            this.InvokeAsync("GetCounty", new object[] {
                        pcode}, this.GetCountyOperationCompleted, userState);
        }
        
        private void OnGetCountyOperationCompleted(object arg) {
            if ((this.GetCountyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountyCompleted(this, new GetCountyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveHHTArea", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveHHTArea(string value) {
            object[] results = this.Invoke("SaveHHTArea", new object[] {
                        value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveHHTAreaAsync(string value) {
            this.SaveHHTAreaAsync(value, null);
        }
        
        /// <remarks/>
        public void SaveHHTAreaAsync(string value, object userState) {
            if ((this.SaveHHTAreaOperationCompleted == null)) {
                this.SaveHHTAreaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveHHTAreaOperationCompleted);
            }
            this.InvokeAsync("SaveHHTArea", new object[] {
                        value}, this.SaveHHTAreaOperationCompleted, userState);
        }
        
        private void OnSaveHHTAreaOperationCompleted(object arg) {
            if ((this.SaveHHTAreaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveHHTAreaCompleted(this, new SaveHHTAreaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHHTAreaRemark", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHHTAreaRemark(string value) {
            object[] results = this.Invoke("GetHHTAreaRemark", new object[] {
                        value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetHHTAreaRemarkAsync(string value) {
            this.GetHHTAreaRemarkAsync(value, null);
        }
        
        /// <remarks/>
        public void GetHHTAreaRemarkAsync(string value, object userState) {
            if ((this.GetHHTAreaRemarkOperationCompleted == null)) {
                this.GetHHTAreaRemarkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHHTAreaRemarkOperationCompleted);
            }
            this.InvokeAsync("GetHHTAreaRemark", new object[] {
                        value}, this.GetHHTAreaRemarkOperationCompleted, userState);
        }
        
        private void OnGetHHTAreaRemarkOperationCompleted(object arg) {
            if ((this.GetHHTAreaRemarkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHHTAreaRemarkCompleted(this, new GetHHTAreaRemarkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHHTAreaList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHHTAreaList(string value) {
            object[] results = this.Invoke("GetHHTAreaList", new object[] {
                        value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetHHTAreaListAsync(string value) {
            this.GetHHTAreaListAsync(value, null);
        }
        
        /// <remarks/>
        public void GetHHTAreaListAsync(string value, object userState) {
            if ((this.GetHHTAreaListOperationCompleted == null)) {
                this.GetHHTAreaListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHHTAreaListOperationCompleted);
            }
            this.InvokeAsync("GetHHTAreaList", new object[] {
                        value}, this.GetHHTAreaListOperationCompleted, userState);
        }
        
        private void OnGetHHTAreaListOperationCompleted(object arg) {
            if ((this.GetHHTAreaListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHHTAreaListCompleted(this, new GetHHTAreaListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAreaNameCompletedEventHandler(object sender, GetAreaNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAreaNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAreaNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAreaCodeCompletedEventHandler(object sender, GetAreaCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAreaCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAreaCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetProvincesCompletedEventHandler(object sender, GetProvincesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProvincesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProvincesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCityCompletedEventHandler(object sender, GetCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCountyCompletedEventHandler(object sender, GetCountyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SaveHHTAreaCompletedEventHandler(object sender, SaveHHTAreaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveHHTAreaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveHHTAreaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHHTAreaRemarkCompletedEventHandler(object sender, GetHHTAreaRemarkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHHTAreaRemarkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHHTAreaRemarkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHHTAreaListCompletedEventHandler(object sender, GetHHTAreaListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHHTAreaListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHHTAreaListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591